sudo: false
language: python
python:
- 3.5
install:
  - pip install -r ./geulgil-server/requirements.txt
  - pip install coverage
script: true
  - nosetests --with-coverage --coverage report
after_script:
  - coveralls
after_success:
  - codecov
